#pop_size: 100
#num_generations: 100
#mutation_rate: 0.015
#crossover_rate: 0.85
#init_prob: 0.002
#k_tournament: 3
#patience: 20
#diversity_low: 0.1
#diversity_extreme: 0.02
#inject_ratio: 0.15
##pop_size: 40
##num_generations: 60
##mutation_rate: 0.015
##crossover_rate: 0.85
##init_prob: 0.01
##k_tournament: 5
##patience: 20
##diversity_low: 0.1
##diversity_extreme: 0.02
##inject_ratio: 0.1
selection_type: tournament
crossover_type: uniform
pop_size: 50
num_generations: 80
mutation_rate: 0.015
crossover_rate: 0.85
init_prob: 0.01
k_tournament: 5
patience: 30
diversity_low: 0.1
diversity_extreme: 0.02
inject_ratio: 0.1